#!/bin/bash

# Variables
log_d="/dev/sdb1"
limit_percent=0

# Get info
log_dir_info=$(sudo df $log_d | grep -o "[1-9][0-9]*%" | cut -c -1)

# Check
if [[ "$log_dir_info" -ge "$limit_percent" ]]
then
echo "Archiving files from /LOG..."
sudo tar -czvf /BACKUP/last_log.tar.gz -P /LOG
echo "Archivation was complited!"
echo "Clearing logs..."
sudo rm -rf /LOG/*
echo "Complited!"
else
echo "It\`s okay, you can sleep now!"
fi
